name = "Hephaestus"
uuid = "df294e67-85fc-45fd-aded-a1d788fddfcf"
version = "1.0.0-DEV"
authors = ["Demetrius Michael <arrrwalktheplank@gmail.com>"]

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Colors = "0.13.1"
FileIO = "1.17.1"
GeometryBasics = "0.5.10"
LinearAlgebra = "1.12.0"
MeshIO = "0.5.3"
Printf = "1.11.0"
Random = "1.11.0"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
